# Generated by Django 6.0 on 2025-12-06 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='Password',
            field=models.CharField(default='1233', max_length=100),
            preserve_default=False,
        ),
    ]
